import type { Finding, ScanResult, SecurityScore } from '@mcpshield/types';
import { createLogger } from '@mcpshield/logger';

const logger = createLogger('agent:demo');

interface DemoData {
  findings: Finding[];
  scanResult: ScanResult;
  securityScore: SecurityScore;
}

export function loadDemoData(): DemoData {
  logger.info('Loading demo mode data');

  const now = new Date().toISOString();

  const findings: Finding[] = [
    {
      findingId: 'MCPS-S3-001:vulnerable-bucket',
      catalogId: 'MCPS-S3-001',
      title: 'Public S3 Bucket',
      severity: 'critical',
      service: 's3',
      resource: {
        service: 's3',
        type: 'bucket',
        id: 'vulnerable-bucket',
        arn: 'arn:aws:s3:::vulnerable-bucket',
        region: 'us-east-1',
      },
      description: 'S3 bucket allows public access via bucket policy.',
      evidence: { publicAccessBlockMissing: true },
      riskScore: 98,
      detectedAt: now,
      status: 'open',
    },
    {
      findingId: 'MCPS-IAM-001:admin-user',
      catalogId: 'MCPS-IAM-001',
      title: 'AdministratorAccess Attached Directly to IAM User',
      severity: 'critical',
      service: 'iam',
      resource: {
        service: 'iam',
        type: 'user',
        id: 'admin-user',
        arn: 'arn:aws:iam::000000000000:user/admin-user',
        region: 'us-east-1',
      },
      description: 'AdministratorAccess policy is attached directly to IAM user.',
      evidence: { attachedAdminPolicy: 'arn:aws:iam::aws:policy/AdministratorAccess' },
      riskScore: 95,
      detectedAt: now,
      status: 'open',
    },
    {
      findingId: 'MCPS-IAM-002:admin-user',
      catalogId: 'MCPS-IAM-002',
      title: 'Old IAM Access Keys',
      severity: 'critical',
      service: 'iam',
      resource: {
        service: 'iam',
        type: 'user',
        id: 'admin-user',
        arn: 'arn:aws:iam::000000000000:user/admin-user',
        region: 'us-east-1',
      },
      description: 'Active access key not rotated in over 90 days.',
      evidence: { staleActiveKeys: [{ accessKeyId: 'AKIA1234567890EXAMPLE', ageDays: 120 }] },
      riskScore: 90,
      detectedAt: now,
      status: 'open',
    },
    {
      findingId: 'MCPS-EC2-001:sg-vulnerable',
      catalogId: 'MCPS-EC2-001',
      title: 'SSH Open to Internet',
      severity: 'high',
      service: 'ec2',
      resource: {
        service: 'ec2',
        type: 'security-group',
        id: 'sg-vulnerable',
        arn: 'arn:aws:ec2:us-east-1:000000000000:security-group/sg-vulnerable',
        region: 'us-east-1',
      },
      description: 'Security group allows SSH (port 22) from 0.0.0.0/0.',
      evidence: { publicSshRules: [{ IpProtocol: 'tcp', FromPort: 22, ToPort: 22 }] },
      riskScore: 82,
      detectedAt: now,
      status: 'open',
    },
    {
      findingId: 'MCPS-EC2-002:sg-vulnerable',
      catalogId: 'MCPS-EC2-002',
      title: 'RDP Open to Internet',
      severity: 'high',
      service: 'ec2',
      resource: {
        service: 'ec2',
        type: 'security-group',
        id: 'sg-vulnerable',
        arn: 'arn:aws:ec2:us-east-1:000000000000:security-group/sg-vulnerable',
        region: 'us-east-1',
      },
      description: 'Security group allows RDP (port 3389) from 0.0.0.0/0.',
      evidence: { publicRdpRules: [{ IpProtocol: 'tcp', FromPort: 3389, ToPort: 3389 }] },
      riskScore: 80,
      detectedAt: now,
      status: 'open',
    },
    {
      findingId: 'MCPS-S3-002:vulnerable-bucket',
      catalogId: 'MCPS-S3-002',
      title: 'S3 Encryption Disabled',
      severity: 'high',
      service: 's3',
      resource: {
        service: 's3',
        type: 'bucket',
        id: 'vulnerable-bucket',
        arn: 'arn:aws:s3:::vulnerable-bucket',
        region: 'us-east-1',
      },
      description: 'Default encryption is not enabled.',
      evidence: { encryptionConfigured: false },
      riskScore: 72,
      detectedAt: now,
      status: 'open',
    },
    {
      findingId: 'MCPS-S3-003:vulnerable-bucket',
      catalogId: 'MCPS-S3-003',
      title: 'S3 Versioning Disabled',
      severity: 'high',
      service: 's3',
      resource: {
        service: 's3',
        type: 'bucket',
        id: 'vulnerable-bucket',
        arn: 'arn:aws:s3:::vulnerable-bucket',
        region: 'us-east-1',
      },
      description: 'Bucket versioning is not enabled.',
      evidence: { versioningStatus: 'Suspended' },
      riskScore: 70,
      detectedAt: now,
      status: 'open',
    },
    {
      findingId: 'MCPS-CT-001:mcpshield-trail',
      catalogId: 'MCPS-CT-001',
      title: 'CloudTrail Disabled',
      severity: 'high',
      service: 'cloudtrail',
      resource: {
        service: 'cloudtrail',
        type: 'trail',
        id: 'mcpshield-trail',
        arn: 'arn:aws:cloudtrail:us-east-1:000000000000:trail/mcpshield-trail',
        region: 'us-east-1',
      },
      description: 'CloudTrail is not logging.',
      evidence: { isLogging: false },
      riskScore: 78,
      detectedAt: now,
      status: 'open',
    },
    {
      findingId: 'MCPS-IAM-003:account-password-policy',
      catalogId: 'MCPS-IAM-003',
      title: 'Weak Password Policy',
      severity: 'medium',
      service: 'iam',
      resource: {
        service: 'iam',
        type: 'password-policy',
        id: 'account-password-policy',
        region: 'us-east-1',
      },
      description: 'Password policy does not meet minimum requirements.',
      evidence: { minimumPasswordLength: 8 },
      riskScore: 52,
      detectedAt: now,
      status: 'open',
    },
    {
      findingId: 'MCPS-IAM-004:unused-user',
      catalogId: 'MCPS-IAM-004',
      title: 'Unused IAM User',
      severity: 'medium',
      service: 'iam',
      resource: {
        service: 'iam',
        type: 'user',
        id: 'unused-user',
        arn: 'arn:aws:iam::000000000000:user/unused-user',
        region: 'us-east-1',
      },
      description: 'User has no activity in over 90 days.',
      evidence: {},
      riskScore: 45,
      detectedAt: now,
      status: 'open',
    },
    {
      findingId: 'MCPS-IAM-005:admin-user',
      catalogId: 'MCPS-IAM-005',
      title: 'Unused Access Keys',
      severity: 'medium',
      service: 'iam',
      resource: {
        service: 'iam',
        type: 'user',
        id: 'admin-user',
        arn: 'arn:aws:iam::000000000000:user/admin-user',
        region: 'us-east-1',
      },
      description: 'Active access key has no usage in over 90 days.',
      evidence: { unusedActiveKeys: [{ accessKeyId: 'AKIA1234567890EXAMPLE' }] },
      riskScore: 42,
      detectedAt: now,
      status: 'open',
    },
    {
      findingId: 'MCPS-S3-004:vulnerable-bucket',
      catalogId: 'MCPS-S3-004',
      title: 'S3 Logging Disabled',
      severity: 'medium',
      service: 's3',
      resource: {
        service: 's3',
        type: 'bucket',
        id: 'vulnerable-bucket',
        arn: 'arn:aws:s3:::vulnerable-bucket',
        region: 'us-east-1',
      },
      description: 'Server access logging is disabled.',
      evidence: { loggingConfigured: false },
      riskScore: 40,
      detectedAt: now,
      status: 'open',
    },
    {
      findingId: 'MCPS-TAG-001:vulnerable-bucket',
      catalogId: 'MCPS-TAG-001',
      title: 'Missing Resource Tags',
      severity: 'low',
      service: 's3',
      resource: {
        service: 's3',
        type: 'bucket',
        id: 'vulnerable-bucket',
        arn: 'arn:aws:s3:::vulnerable-bucket',
        region: 'us-east-1',
      },
      description: 'Required governance tags are missing.',
      evidence: { missingTags: ['Owner', 'Environment', 'DataClassification'] },
      riskScore: 20,
      detectedAt: now,
      status: 'open',
    },
    {
      findingId: 'MCPS-NAM-001:vulnerable-bucket',
      catalogId: 'MCPS-NAM-001',
      title: 'Poor Naming Convention',
      severity: 'low',
      service: 's3',
      resource: {
        service: 's3',
        type: 'bucket',
        id: 'vulnerable-bucket',
        arn: 'arn:aws:s3:::vulnerable-bucket',
        region: 'us-east-1',
      },
      description: 'Bucket name does not follow naming convention.',
      evidence: { name: 'vulnerable-bucket' },
      riskScore: 15,
      detectedAt: now,
      status: 'open',
    },
    {
      findingId: 'MCPS-DESC-001:sg-vulnerable',
      catalogId: 'MCPS-DESC-001',
      title: 'Missing Resource Description',
      severity: 'low',
      service: 'ec2',
      resource: {
        service: 'ec2',
        type: 'security-group',
        id: 'sg-vulnerable',
        arn: 'arn:aws:ec2:us-east-1:000000000000:security-group/sg-vulnerable',
        region: 'us-east-1',
      },
      description: 'Security group has no description.',
      evidence: { description: '' },
      riskScore: 12,
      detectedAt: now,
      status: 'open',
    },
  ];

  const scanResult: ScanResult = {
    scanId: 'demo_scan_001',
    startedAt: now,
    completedAt: now,
    endpoint: 'http://localhost:4566',
    region: 'us-east-1',
    resourcesScanned: 15,
    resourceCounts: {
      s3: 4,
      iam: 5,
      ec2: 1,
      cloudtrail: 1,
      lambda: 1,
      sqs: 1,
      sns: 1,
      secretsmanager: 1,
      ssm: 1,
      dynamodb: 1,
      cloudwatch: 1,
    },
    findings: findings.filter((f) => f.status === 'open'),
  };

  const securityScore: SecurityScore = {
    score: 36,
    grade: 'F',
    totalFindings: findings.length,
    breakdown: { critical: 3, high: 5, medium: 4, low: 3 },
    computedAt: now,
  };

  return { findings, scanResult, securityScore };
}
